apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 4.9.0

dependencies:
- name: ingress-nginx
  version: 4.9.0
  repository: https://kubernetes.github.io/ingress-nginx