apiVersion: v1
kind: Service
metadata:
  labels:
    app: planets-service
  name: planets-service
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: planets-service
  type: ClusterIP