apiVersion: v2
name: openunison
description: A Helm chart for Kubernetes
type: application
version: 2.3.38

dependencies:
- name: openunison
  version: 2.3.38
  repository: https://nexus.tremolo.io/repository/helm