apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/vikinglabs/k8s-demo-cfg.git
              revision: HEAD
              files:
                - path: "/*"
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/vikinglabs/k8s-demo-cfg.git
        targetRevision: HEAD
        path: "/"
      destination:
        server: '{{server}}'
        namespace: guestbook