apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: true
        - name: MYSQL_DATABASE
          value: bookstore
        - name: MYSQL_USER
          value: appuser
        - name: MYSQL_PASSWORD
          value: appuser123
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: volume
  volumeClaimTemplates:
  - metadata:
      name: volume
    spec:
      storageClassName: standard
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi