apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: drone
spec:
  hosts:
  - drone.localtest.me
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: drone.drone.svc.cluster.local