apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  components:
    ingressGateways:
    - namespace: istio-system
      name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - name: status-port
              port: 15021
            - name: tls
              port: 15443
              nodePort: 31371
            - name: http2
              port: 80
              nodePort: 31381
              targetPort: 8280
            - name: https
              port: 443
              nodePort: 31391
              targetPort: 8243
  addonComponents:
    prometheus:
      enabled: false