apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: satellites-service
  name: satellites-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satellites-service
  template:
    metadata:
      labels:
        app: satellites-service
    spec:
      containers:
      - image: docker.io/lmctague/satellites-service:8665318884a4f7919ab45734fdb87cd7213a0626
        name: satellites-service
        ports:
        - name: http
          containerPort: 80
        #livenessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        #readinessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        env:
        - name: DATABASE_URL 
          value: "postgres://satellites_user:b0sHYNKUuGcu6P2n@postgres-postgresql.demo.svc.cluster.local/satellites"
        - name: PASSWORD_SECRET_KEY
          value: ""
        - name: JWT_SECRET_KEY
          value: ""
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"