apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - image: docker.io/lmctague/auth-service:8665318884a4f7919ab45734fdb87cd7213a0626
        name: auth-service
        ports:
        - name: http
          containerPort: 80
        #livenessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        #readinessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        env:
        - name: DATABASE_URL
          value: "postgres://users_user:94nZL2HtN51yAwKs@postgres-postgresql.demo.svc.cluster.local/users"
        - name: PASSWORD_SECRET_KEY
          value: "test_key"
        - name: JWT_SECRET_KEY
          value: "secret_key"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"