apiVersion: v1
kind: Service
metadata:
  labels:
    app: apollo-router
  name: apollo-router 
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: apollo-router
  type: ClusterIP