apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apollo-router
  name: apollo-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-router
  template:
    metadata:
      labels:
        app: apollo-router
    spec:
      containers:
      - image: lmctague/apollo-router:8665318884a4f7919ab45734fdb87cd7213a0626
        name: apollo-router
        ports:
        - name: http
          containerPort: 80
        - name: health-check
          containerPort: 8088
        #livenessProbe:
        #  httpGet:
        #    path: "/health"
        #    port: health-check
        #readinessProbe:
        #  httpGet:
        #    path: "/health"
        #    port: health-check
        env:
        - name: APOLLO_ROUTER_SUPERGRAPH_PATH 
          value: "/apollo-router/schema/supergraph.graphql"
        - name: APOLLO_ROUTER_CONFIG_PATH
          value: "/apollo-router/config/router.yaml"
        - name: APOLLO_ROUTER_LOG
          value: "debug"
        - name: APOLLO_TELEMETRY_DISABLED
          value: "1"
        - name: JWT_SECRET_KEY
          value: "secret-key"
        resources:
          requests:
            memory: "500Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: supergraph-config
          mountPath: /apollo-router/schema
        - name: router-config
          mountPath: /apollo-router/config
      volumes:
      - name: supergraph-config
        configMap:
          name: supergraph-config
      - name: router-config
        configMap:
          name: router-config