apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apollo-router
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apollo-router
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50