resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ./hpa.yaml

namespace: demo

commonLabels:
  app: apollo-router

configMapGenerator:
- name: supergraph-config
  files:
  - ./supergraph.graphql
- name: router-config
  files:
  - ./router.yaml