apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: planets-service
  name: planets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planets-service
  template:
    metadata:
      labels:
        app: planets-service
    spec:
      containers:
      - image: docker.io/lmctague/planets-service:8665318884a4f7919ab45734fdb87cd7213a0626
        name: planets-service
        ports:
        - name: http
          containerPort: 80
        #livenessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        #readinessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        env:
        - name: DATABASE_URL 
          value: "postgres://planets_user:7O2Beg8FlCJvJsQL@postgres-postgresql.demo.svc.cluster.local/planets"
        - name: KAFKA_BROKER
          value: "kafka.demo.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "demo_topic"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"