apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apollo-router
  namespace: argocd
spec:
  project: default
  source:
    path: apollo-router/overlays/development
    repoURL: 'https://github.com/shipwright-sh/k8s-demo-cfg.git'
    targetRevision: HEAD
  destination:
    namespace: demo
    sever: {{ }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    validate: true