apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apollo-router
spec:
  destination:
    name: ''
    namespace: demo
    server: 'https://kubernetes.default.svc'
  source:
    path: apollo-router/overlays/development
    repoURL: 'https://github.com/shipwright-sh/k8s-demo-cfg.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false