apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: satellites-service
spec:
  destination:
    namespace: demo
  source:
    path: satellites-service/overlays/development
    repoURL: 'https://github.com/shipwright-sh/k8s-demo-cfg.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false