resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: planets-service
  path: deployment-patch.yaml
- target:
    kind: HorizontalPodAutoscaler
    name: planets-service
  path: hpa-patch.yaml